package diffgen

import (
	"fmt"
	"strings"

	"github.com/NickKL05/pgfleet/internal/drift/model"
	"github.com/NickKL05/pgfleet/internal/report"
)

// quoteIdent quotes a PostgreSQL identifier, doubling embedded quotes.
func quoteIdent(ident string) string {
	return `"` + strings.ReplaceAll(ident, `"`, `""`) + `"`
}

// ensureSemicolon appends a trailing semicolon if the statement lacks one.
// pg_get_indexdef and pg_get_triggerdef return statements without one.
func ensureSemicolon(s string) string {
	s = strings.TrimRight(s, " \n\t")
	if strings.HasSuffix(s, ";") {
		return s
	}
	return s + ";"
}

// columnDDL renders a single column definition for CREATE TABLE or ADD COLUMN.
func columnDDL(c *model.Column) string {
	parts := []string{quoteIdent(c.Name), c.Type}
	switch {
	case c.Identity == "a":
		parts = append(parts, "GENERATED ALWAYS AS IDENTITY")
	case c.Identity == "d":
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
	case c.Generated:
		// For a generated column the stored expression lives in the default slot.
		parts = append(parts, fmt.Sprintf("GENERATED ALWAYS AS (%s) STORED", c.Default))
		if c.NotNull {
			parts = append(parts, "NOT NULL")
		}
	default:
		if c.NotNull {
			parts = append(parts, "NOT NULL")
		}
		if c.Default != "" {
			parts = append(parts, "DEFAULT "+c.Default)
		}
	}
	return strings.Join(parts, " ")
}

// createTableDDL renders a CREATE TABLE with columns only; constraints and
// indexes are added by later statements in the plan.
func createTableDDL(t *model.Table) string {
	cols := make([]string, 0, len(t.Columns))
	for _, c := range t.Columns {
		cols = append(cols, "    "+columnDDL(c))
	}
	return fmt.Sprintf("CREATE TABLE %s (\n%s\n);", quoteIdent(t.Name), strings.Join(cols, ",\n"))
}

// addConstraintDDL renders ALTER TABLE ... ADD CONSTRAINT using the normalized
// constraint definition (e.g. "PRIMARY KEY (id)").
func addConstraintDDL(table string, c *model.Constraint) string {
	return fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s %s;", quoteIdent(table), quoteIdent(c.Name), c.Definition)
}

// alterColumnDDL renders the ALTER statements needed to bring a column in line
// with the reference. Changes it cannot express (identity, generated, position)
// are appended to skipped.
func alterColumnDDL(table, col string, ref *model.Column, changes []report.FieldChange, skipped *[]Skipped) []string {
	var out []string
	for _, ch := range changes {
		switch ch.Field {
		case "type":
			out = append(out, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s;", quoteIdent(table), quoteIdent(col), ref.Type))
		case "nullability":
			if ref.NotNull {
				out = append(out, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL;", quoteIdent(table), quoteIdent(col)))
			} else {
				out = append(out, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL;", quoteIdent(table), quoteIdent(col)))
			}
		case "default":
			if ref.Default != "" {
				out = append(out, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s;", quoteIdent(table), quoteIdent(col), ref.Default))
			} else {
				out = append(out, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT;", quoteIdent(table), quoteIdent(col)))
			}
		default:
			*skipped = append(*skipped, Skipped{
				Object: fmt.Sprintf("column %s.%s", table, col),
				Reason: fmt.Sprintf("%s change (%s -> %s) needs manual handling", ch.Field, ch.From, ch.To),
			})
		}
	}
	return out
}

// createSequenceDDL renders a CREATE SEQUENCE with structural attributes only.
func createSequenceDDL(s *model.Sequence) string {
	return fmt.Sprintf("CREATE SEQUENCE %s AS %s INCREMENT BY %d MINVALUE %d MAXVALUE %d START WITH %d %s;",
		quoteIdent(s.Name), s.DataType, s.Increment, s.Min, s.Max, s.Start, cycleClause(s.Cycle))
}

// alterSequenceDDL adjusts a sequence's structural attributes.
func alterSequenceDDL(s *model.Sequence) string {
	return fmt.Sprintf("ALTER SEQUENCE %s AS %s INCREMENT BY %d MINVALUE %d MAXVALUE %d %s;",
		quoteIdent(s.Name), s.DataType, s.Increment, s.Min, s.Max, cycleClause(s.Cycle))
}

func cycleClause(cycle bool) string {
	if cycle {
		return "CYCLE"
	}
	return "NO CYCLE"
}

// createEnumDDL renders CREATE TYPE ... AS ENUM with labels in order.
func createEnumDDL(e *model.EnumType) string {
	labels := make([]string, len(e.Labels))
	for i, l := range e.Labels {
		labels[i] = "'" + strings.ReplaceAll(l, "'", "''") + "'"
	}
	return fmt.Sprintf("CREATE TYPE %s AS ENUM (%s);", quoteIdent(e.Name), strings.Join(labels, ", "))
}

// indexDef finds the reference definition for an index by name.
func indexDef(ref *model.Schema, name string) string {
	for _, t := range ref.Tables {
		if idx, ok := t.Indexes[name]; ok {
			return idx.Definition
		}
	}
	return ""
}

// tableOfIndex returns the table owning the named index in the reference.
func tableOfIndex(ref *model.Schema, name string) (string, bool) {
	for _, t := range ref.Tables {
		if _, ok := t.Indexes[name]; ok {
			return t.Name, true
		}
	}
	return "", false
}
