// Package diffgen produces object-level and field-level differences between a
// reference schema model and a tenant schema model. The hash-level Diff in the
// fingerprint package answers "did anything change"; diffgen answers "what
// exactly changed", including the field-level explanation for modified columns
// and constraints (R5.6).
package diffgen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/NickKL05/pgfleet/internal/drift/model"
	"github.com/NickKL05/pgfleet/internal/report"
)

// Classification of one object-level difference.
const (
	Missing  = "missing"
	Extra    = "extra"
	Modified = "modified"
)

// Compare returns the differences of tenant against reference, sorted by
// (type, name). The same flatten options are applied to both sides so the
// comparison respects the ignore list and column-order setting.
func Compare(reference, tenant *model.Schema, opts model.Options) []report.ObjectDiff {
	ref := flattenMap(reference, opts)
	ten := flattenMap(tenant, opts)

	keys := make([]string, 0, len(ref)+len(ten))
	seen := map[string]bool{}
	for k := range ref {
		keys = append(keys, k)
		seen[k] = true
	}
	for k := range ten {
		if !seen[k] {
			keys = append(keys, k)
		}
	}

	var diffs []report.ObjectDiff
	for _, k := range keys {
		r, inRef := ref[k]
		t, inTen := ten[k]
		switch {
		case inRef && !inTen:
			diffs = append(diffs, report.ObjectDiff{Type: r.Type, Name: r.Name, Class: Missing})
		case !inRef && inTen:
			diffs = append(diffs, report.ObjectDiff{Type: t.Type, Name: t.Name, Class: Extra})
		case r.Body != t.Body:
			diffs = append(diffs, report.ObjectDiff{
				Type:    r.Type,
				Name:    r.Name,
				Class:   Modified,
				Changes: explain(r, t, reference, tenant, opts),
			})
		}
	}

	sort.Slice(diffs, func(i, j int) bool {
		if diffs[i].Type != diffs[j].Type {
			return diffs[i].Type < diffs[j].Type
		}
		return diffs[i].Name < diffs[j].Name
	})
	return diffs
}

// flattenMap keys a schema's flattened objects by "type\x00name".
func flattenMap(s *model.Schema, opts model.Options) map[string]model.FlatObject {
	if s == nil {
		return map[string]model.FlatObject{}
	}
	out := map[string]model.FlatObject{}
	for _, o := range s.Flatten(opts) {
		out[o.Type+"\x00"+o.Name] = o
	}
	return out
}

// explain produces the field-level changes for a modified object. Columns and
// constraints get a structured field breakdown; other object types fall back to
// a single before/after of their canonical definition, which is still useful.
func explain(refObj, tenObj model.FlatObject, reference, tenant *model.Schema, opts model.Options) []report.FieldChange {
	switch refObj.Type {
	case model.KindColumn:
		table, col := splitName(refObj.Name)
		return diffColumns(reference.Column(table, col), tenant.Column(table, col), opts)
	case model.KindConstraint:
		table, name := splitName(refObj.Name)
		return diffConstraints(reference.Constraint(table, name), tenant.Constraint(table, name))
	default:
		return []report.FieldChange{{Field: "definition", From: refObj.Body, To: tenObj.Body}}
	}
}

func diffColumns(ref, ten *model.Column, opts model.Options) []report.FieldChange {
	if ref == nil || ten == nil {
		return nil
	}
	var ch []report.FieldChange
	add := func(field, from, to string) {
		if from != to {
			ch = append(ch, report.FieldChange{Field: field, From: from, To: to})
		}
	}
	add("type", ref.Type, ten.Type)
	add("nullability", nullText(ref.NotNull), nullText(ten.NotNull))
	add("default", ref.Default, ten.Default)
	add("generated", strconv.FormatBool(ref.Generated), strconv.FormatBool(ten.Generated))
	add("identity", identityText(ref.Identity), identityText(ten.Identity))
	if !opts.IgnoreColumnOrder {
		add("position", strconv.Itoa(ref.Position), strconv.Itoa(ten.Position))
	}
	return ch
}

func diffConstraints(ref, ten *model.Constraint) []report.FieldChange {
	if ref == nil || ten == nil {
		return nil
	}
	var ch []report.FieldChange
	if ref.Type != ten.Type {
		ch = append(ch, report.FieldChange{Field: "kind", From: constraintKind(ref.Type), To: constraintKind(ten.Type)})
	}
	if ref.Definition != ten.Definition {
		ch = append(ch, report.FieldChange{Field: "definition", From: ref.Definition, To: ten.Definition})
	}
	return ch
}

func splitName(name string) (table, object string) {
	parts := strings.SplitN(name, ".", 2)
	if len(parts) != 2 {
		return name, ""
	}
	return parts[0], parts[1]
}

func nullText(notNull bool) string {
	if notNull {
		return "not null"
	}
	return "nullable"
}

func identityText(id string) string {
	switch id {
	case "a":
		return "generated always"
	case "d":
		return "generated by default"
	default:
		return "none"
	}
}

func constraintKind(t string) string {
	switch t {
	case "p":
		return "primary key"
	case "f":
		return "foreign key"
	case "u":
		return "unique"
	case "c":
		return "check"
	default:
		return fmt.Sprintf("constraint(%s)", t)
	}
}
